### ISSUE TITLE
Syntax Error: Non-ASCII character Line 9

### ISSUE THREAD

**Issue by davidcayll** [lk-geimfari/rmanns#3]
Hi, I have been trying to use the work done here without success.  Using MacBook Pro with OSX 10.11.3.  Installed the pdftk version 2.02 server edition downloaded from the www.pdflabs.com site.  Several issues, 1) found that on command line had to use "python ./rmanns.py" syntax rather than the "python3..." syntax suggested elsewhere, 2)  had runtime Syntax Error: Non-ASCII character Line 88 requiring using the "raw_input" syntax rather than the "input" syntax in this code, 3) now have outstanding Syntax Error: Non-ASCII character Line 9 which is currently outstanding requiring resolution.  

I am a newbee to Python script language and have been studing the pdftk manual and tutorials on the correct syntax.  I could not find a pdftk command using "sed" since it seemed all pdftk commands begin with "pdftk" along with the various command line arguments.  

Anyone have a suggestion for modifying the Line 9 or Line 83 where it is called from?

**Comment by lk-geimfari** [comment]
@davidcayll Try to comment all `print` functions in `rmanns.py`. Possibly issue related to colored output.

**Comment by davidcayll** [comment]
@lk-geimfari thanks for your reply.  I inquired as to the version of Python running on my MacBook running OSX 10.11.6 El Captian, and it came back as 2.7.10.  Some the previous discussion here was on correcting the script syntax for Python 3.  Is it significant if my OSX is running 2.7.10 while the rmanns.py script is for 3...?  I am not familiar enough with Python to know what the differences are.  Maybe I need to update my OSX for Python 3, is that possible? or needed?

Just a few questions before I begin commenting out the printing to screen and other troubleshooting, it seems to print the status comments fine in lime green on my screen as it runs - it just has error messages and ends up deleting the pdf file without rewriting it.

**Comment by lk-geimfari** [comment]
@davidcayl Do you have preinstalled `sed` on your OS? If you do, then you just need to [install](https://stackoverflow.com/questions/33535625/python-3-5-for-os-x-el-capitan) Python 3.4 or higher.

**Comment by davidcayll** [comment]
@lk-geimfari I am getting closer to getting everything set up to run this python3 script.  I did find a sed on my Mac but not sure if it is the preinstalled BSD.  I installed Python 3.6.4 and figured out how to edit the path file for it to run.  I also found out the default TextEdit on Mac does not always save text files in ASCII text - this was one of the errors I had.  Now using TextWrangler.  I think I need to update the path file again with the sed path or do I need the GNU sed function for this script?  Getting closer, sorry for the newbie stuff.  Now just to find that file location again!

**Comment by davidcayll** [comment]
@lk-geimfari Thanks for the command lines above.  I would like to get my mac correctly set up to execute Python3.  It seems a mac osx little more complex than my windows pc.

I have the preinstalled sed in /usr/bin/ folder and this path is in the path file.  But it seems that sed has a problem.  Of course after the sed: RE error everything else errors out.  Should this sed be the GNU sed instead of the preinstalled BSD sed?  Here is the results of running the script on the original code file:

Uncompressing...
Removing annotations...
sed: RE error: illegal byte sequence
Compressing...
Error: Unable to find file.
Error: Failed to open PDF file: 
   Csharp_Deconstructed.pdf2
Errors encountered.  No output created.
Done.  Input errors, so no output created.
Annotations removed from file: Csharp_Deconstructed.pdf.

**Comment by lk-geimfari** [comment]
@davidcayll The script removes only annotations which hardcoded in `ANNOTATIONS`. Unfortunately, you should update this list for specific case manually.

**Comment by lk-geimfari** [comment]
@davidcayll Great! Thank you for interest!

**Comment by davidcayll** [comment]
@lk-geimfari Thanks for your quick responses in this issue.  Should mention the special conditions this script s meant or.  Like Python3 needs to be installed separately and dependent on GNU-sed whicneeds to be installed separately.  Closing out my issue.
