### ISSUE TITLE
It just removes the watermark text, not remove the link attacked to the watermark

### ISSUE THREAD

**Issue by phplaw** [lk-geimfari/rmanns#4]
Same as title: It just removes the watermark text, does not remove the link attacked to the watermark

**Comment by jaranda** [comment]
add
'-e "s/\/URI/ /" ',
to the ANNOTATIONS list

**Comment by phplaw** [comment]
> add
> '-e "s//URI/ /" ',
> to the ANNOTATIONS list

That could not fix the issue because of URI already exists in ANNOTATIONS list.

**Comment by jaranda** [comment]
It's has been added to the main branch
